# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowNew.ui'
#
# Created: Wed Oct 02 13:52:19 2019
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

from Laminas import Laminas
from Bobbins import Bobbins
from Wires import Wires

from Lamina import Lamina
from Bobbin import Bobbin
from Wire import Wire 
from Transformer import Transformer

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogNew(object):
    def setupUi(self, DialogNew):
        DialogNew.setObjectName(_fromUtf8("DialogNew"))
        DialogNew.resize(620, 583)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("iconPower.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogNew.setWindowIcon(icon)
        self.groupBox_general = QtGui.QGroupBox(DialogNew)
        self.groupBox_general.setGeometry(QtCore.QRect(340, 10, 271, 221))
        self.groupBox_general.setObjectName(_fromUtf8("groupBox_general"))
        self.label_frequency = QtGui.QLabel(self.groupBox_general)
        self.label_frequency.setGeometry(QtCore.QRect(10, 25, 55, 14))
        self.label_frequency.setObjectName(_fromUtf8("label_frequency"))
        self.lineEdit_frequency = QtGui.QLineEdit(self.groupBox_general)
        self.lineEdit_frequency.setGeometry(QtCore.QRect(80, 20, 80, 20))
        self.lineEdit_frequency.setObjectName(_fromUtf8("lineEdit_frequency"))
        self.label_tempReference = QtGui.QLabel(self.groupBox_general)
        self.label_tempReference.setGeometry(QtCore.QRect(10, 55, 90, 14))
        self.label_tempReference.setObjectName(_fromUtf8("label_tempReference"))
        self.lineEdit_tempReference = QtGui.QLineEdit(self.groupBox_general)
        self.lineEdit_tempReference.setGeometry(QtCore.QRect(110, 50, 80, 20))
        self.lineEdit_tempReference.setObjectName(_fromUtf8("lineEdit_tempReference"))
        self.label_flux = QtGui.QLabel(self.groupBox_general)
        self.label_flux.setGeometry(QtCore.QRect(10, 85, 46, 13))
        self.label_flux.setObjectName(_fromUtf8("label_flux"))
        self.lineEdit_flux = QtGui.QLineEdit(self.groupBox_general)
        self.lineEdit_flux.setGeometry(QtCore.QRect(50, 80, 80, 20))
        self.lineEdit_flux.setObjectName(_fromUtf8("lineEdit_flux"))
        self.label_currentDensity = QtGui.QLabel(self.groupBox_general)
        self.label_currentDensity.setGeometry(QtCore.QRect(10, 115, 115, 16))
        self.label_currentDensity.setObjectName(_fromUtf8("label_currentDensity"))
        self.lineEdit_currentDensity = QtGui.QLineEdit(self.groupBox_general)
        self.lineEdit_currentDensity.setGeometry(QtCore.QRect(130, 110, 80, 20))
        self.lineEdit_currentDensity.setObjectName(_fromUtf8("lineEdit_currentDensity"))
        self.label_style = QtGui.QLabel(self.groupBox_general)
        self.label_style.setGeometry(QtCore.QRect(10, 145, 111, 16))
        self.label_style.setObjectName(_fromUtf8("label_style"))
        self.comboBox_style = QtGui.QComboBox(self.groupBox_general)
        self.comboBox_style.setGeometry(QtCore.QRect(120, 140, 141, 22))
        self.comboBox_style.setObjectName(_fromUtf8("comboBox_style"))
        self.comboBox_style.addItem(_fromUtf8(""))
        self.comboBox_style.addItem(_fromUtf8(""))
        self.comboBox_style.addItem(_fromUtf8(""))
        self.comboBox_style.addItem(_fromUtf8(""))
        self.label_lamina = QtGui.QLabel(self.groupBox_general)
        self.label_lamina.setGeometry(QtCore.QRect(10, 180, 81, 14))
        self.label_lamina.setObjectName(_fromUtf8("label_lamina"))
        self.comboBox_lamina = QtGui.QComboBox(self.groupBox_general)
        self.comboBox_lamina.setGeometry(QtCore.QRect(90, 180, 69, 22))
        self.comboBox_lamina.setObjectName(_fromUtf8("comboBox_lamina"))
        self.comboBox_lamina.addItem(_fromUtf8(""))
        self.comboBox_lamina.addItem(_fromUtf8(""))
        self.comboBox_lamina.addItem(_fromUtf8(""))
        self.groupBox = QtGui.QGroupBox(DialogNew)
        self.groupBox.setGeometry(QtCore.QRect(10, 130, 321, 101))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.checkBox_compensation = QtGui.QCheckBox(self.groupBox)
        self.checkBox_compensation.setGeometry(QtCore.QRect(10, 20, 91, 17))
        self.checkBox_compensation.setObjectName(_fromUtf8("checkBox_compensation"))
        self.lineEdit_compensation = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_compensation.setGeometry(QtCore.QRect(110, 20, 113, 20))
        self.lineEdit_compensation.setObjectName(_fromUtf8("lineEdit_compensation"))
        self.pushButton_calculate = QtGui.QPushButton(DialogNew)
        self.pushButton_calculate.setGeometry(QtCore.QRect(10, 240, 601, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_calculate.setFont(font)
        self.pushButton_calculate.setObjectName(_fromUtf8("pushButton_calculate"))
        self.groupBox_Output = QtGui.QGroupBox(DialogNew)
        self.groupBox_Output.setGeometry(QtCore.QRect(10, 10, 151, 111))
        self.groupBox_Output.setObjectName(_fromUtf8("groupBox_Output"))
        self.label_voltageOut = QtGui.QLabel(self.groupBox_Output)
        self.label_voltageOut.setGeometry(QtCore.QRect(10, 55, 50, 14))
        self.label_voltageOut.setObjectName(_fromUtf8("label_voltageOut"))
        self.label_powerOut = QtGui.QLabel(self.groupBox_Output)
        self.label_powerOut.setGeometry(QtCore.QRect(10, 25, 50, 14))
        self.label_powerOut.setObjectName(_fromUtf8("label_powerOut"))
        self.label_currentOut = QtGui.QLabel(self.groupBox_Output)
        self.label_currentOut.setGeometry(QtCore.QRect(10, 85, 50, 14))
        self.label_currentOut.setObjectName(_fromUtf8("label_currentOut"))
        self.lineEdit_powerOut = QtGui.QLineEdit(self.groupBox_Output)
        self.lineEdit_powerOut.setGeometry(QtCore.QRect(60, 20, 80, 20))
        self.lineEdit_powerOut.setObjectName(_fromUtf8("lineEdit_powerOut"))
        self.lineEdit_voltageOut = QtGui.QLineEdit(self.groupBox_Output)
        self.lineEdit_voltageOut.setGeometry(QtCore.QRect(60, 50, 80, 20))
        self.lineEdit_voltageOut.setObjectName(_fromUtf8("lineEdit_voltageOut"))
        self.lineEdit_currentOut = QtGui.QLineEdit(self.groupBox_Output)
        self.lineEdit_currentOut.setGeometry(QtCore.QRect(60, 80, 80, 20))
        self.lineEdit_currentOut.setObjectName(_fromUtf8("lineEdit_currentOut"))
        self.tabWidget = QtGui.QTabWidget(DialogNew)
        self.tabWidget.setGeometry(QtCore.QRect(10, 290, 601, 241))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.result_1 = QtGui.QWidget()
        self.result_1.setObjectName(_fromUtf8("result_1"))
        self.groupBox_output_result = QtGui.QGroupBox(self.result_1)
        self.groupBox_output_result.setGeometry(QtCore.QRect(12, 10, 231, 195))
        self.groupBox_output_result.setObjectName(_fromUtf8("groupBox_output_result"))
        self.label_powerOut_result = QtGui.QLabel(self.groupBox_output_result)
        self.label_powerOut_result.setGeometry(QtCore.QRect(10, 20, 120, 16))
        self.label_powerOut_result.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_powerOut_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_powerOut_result.setObjectName(_fromUtf8("label_powerOut_result"))
        self.lineEdit_voltageOut_result = QtGui.QLineEdit(self.groupBox_output_result)
        self.lineEdit_voltageOut_result.setGeometry(QtCore.QRect(135, 45, 80, 20))
        self.lineEdit_voltageOut_result.setObjectName(_fromUtf8("lineEdit_voltageOut_result"))
        self.label_awgWireOut_result = QtGui.QLabel(self.groupBox_output_result)
        self.label_awgWireOut_result.setGeometry(QtCore.QRect(10, 110, 120, 13))
        self.label_awgWireOut_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_awgWireOut_result.setObjectName(_fromUtf8("label_awgWireOut_result"))
        self.lineEdit_awgWireOut_result = QtGui.QLineEdit(self.groupBox_output_result)
        self.lineEdit_awgWireOut_result.setGeometry(QtCore.QRect(135, 105, 80, 20))
        self.lineEdit_awgWireOut_result.setObjectName(_fromUtf8("lineEdit_awgWireOut_result"))
        self.lineEdit_turnOut_result = QtGui.QLineEdit(self.groupBox_output_result)
        self.lineEdit_turnOut_result.setGeometry(QtCore.QRect(135, 135, 80, 20))
        self.lineEdit_turnOut_result.setObjectName(_fromUtf8("lineEdit_turnOut_result"))
        self.label_densityOut_result = QtGui.QLabel(self.groupBox_output_result)
        self.label_densityOut_result.setGeometry(QtCore.QRect(10, 170, 120, 16))
        self.label_densityOut_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_densityOut_result.setObjectName(_fromUtf8("label_densityOut_result"))
        self.lineEdit_currentOut_output = QtGui.QLineEdit(self.groupBox_output_result)
        self.lineEdit_currentOut_output.setGeometry(QtCore.QRect(135, 75, 80, 20))
        self.lineEdit_currentOut_output.setObjectName(_fromUtf8("lineEdit_currentOut_output"))
        self.lineEdit_powerOut_result = QtGui.QLineEdit(self.groupBox_output_result)
        self.lineEdit_powerOut_result.setGeometry(QtCore.QRect(135, 15, 80, 20))
        self.lineEdit_powerOut_result.setObjectName(_fromUtf8("lineEdit_powerOut_result"))
        self.label_currentOut_result = QtGui.QLabel(self.groupBox_output_result)
        self.label_currentOut_result.setGeometry(QtCore.QRect(10, 80, 120, 16))
        self.label_currentOut_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_currentOut_result.setObjectName(_fromUtf8("label_currentOut_result"))
        self.label_voltageOut_result = QtGui.QLabel(self.groupBox_output_result)
        self.label_voltageOut_result.setGeometry(QtCore.QRect(10, 50, 120, 16))
        self.label_voltageOut_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_voltageOut_result.setObjectName(_fromUtf8("label_voltageOut_result"))
        self.label_turnOut_result = QtGui.QLabel(self.groupBox_output_result)
        self.label_turnOut_result.setGeometry(QtCore.QRect(10, 140, 120, 20))
        self.label_turnOut_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_turnOut_result.setObjectName(_fromUtf8("label_turnOut_result"))
        self.lineEdit_densityOut_result = QtGui.QLineEdit(self.groupBox_output_result)
        self.lineEdit_densityOut_result.setGeometry(QtCore.QRect(135, 165, 80, 20))
        self.lineEdit_densityOut_result.setObjectName(_fromUtf8("lineEdit_densityOut_result"))
        self.groupBox_input_result = QtGui.QGroupBox(self.result_1)
        self.groupBox_input_result.setGeometry(QtCore.QRect(350, 10, 231, 195))
        self.groupBox_input_result.setObjectName(_fromUtf8("groupBox_input_result"))
        self.label_powerIn_result = QtGui.QLabel(self.groupBox_input_result)
        self.label_powerIn_result.setGeometry(QtCore.QRect(10, 20, 120, 16))
        self.label_powerIn_result.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_powerIn_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_powerIn_result.setObjectName(_fromUtf8("label_powerIn_result"))
        self.lineEdit_voltageIn_result = QtGui.QLineEdit(self.groupBox_input_result)
        self.lineEdit_voltageIn_result.setGeometry(QtCore.QRect(135, 45, 80, 20))
        self.lineEdit_voltageIn_result.setObjectName(_fromUtf8("lineEdit_voltageIn_result"))
        self.label_awgWireIn_result = QtGui.QLabel(self.groupBox_input_result)
        self.label_awgWireIn_result.setGeometry(QtCore.QRect(10, 110, 120, 13))
        self.label_awgWireIn_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_awgWireIn_result.setObjectName(_fromUtf8("label_awgWireIn_result"))
        self.lineEdit_awgWireIn_result = QtGui.QLineEdit(self.groupBox_input_result)
        self.lineEdit_awgWireIn_result.setGeometry(QtCore.QRect(135, 105, 80, 20))
        self.lineEdit_awgWireIn_result.setObjectName(_fromUtf8("lineEdit_awgWireIn_result"))
        self.lineEdit_turnIn_result = QtGui.QLineEdit(self.groupBox_input_result)
        self.lineEdit_turnIn_result.setGeometry(QtCore.QRect(135, 135, 80, 20))
        self.lineEdit_turnIn_result.setObjectName(_fromUtf8("lineEdit_turnIn_result"))
        self.label_densityIn_result = QtGui.QLabel(self.groupBox_input_result)
        self.label_densityIn_result.setGeometry(QtCore.QRect(10, 170, 120, 16))
        self.label_densityIn_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_densityIn_result.setObjectName(_fromUtf8("label_densityIn_result"))
        self.lineEdit_currentIn_result = QtGui.QLineEdit(self.groupBox_input_result)
        self.lineEdit_currentIn_result.setGeometry(QtCore.QRect(135, 75, 80, 20))
        self.lineEdit_currentIn_result.setObjectName(_fromUtf8("lineEdit_currentIn_result"))
        self.lineEdit_powerIn_result = QtGui.QLineEdit(self.groupBox_input_result)
        self.lineEdit_powerIn_result.setGeometry(QtCore.QRect(135, 15, 80, 20))
        self.lineEdit_powerIn_result.setObjectName(_fromUtf8("lineEdit_powerIn_result"))
        self.label_currentIn_result = QtGui.QLabel(self.groupBox_input_result)
        self.label_currentIn_result.setGeometry(QtCore.QRect(10, 80, 120, 16))
        self.label_currentIn_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_currentIn_result.setObjectName(_fromUtf8("label_currentIn_result"))
        self.label_voltageIn_result = QtGui.QLabel(self.groupBox_input_result)
        self.label_voltageIn_result.setGeometry(QtCore.QRect(10, 50, 120, 16))
        self.label_voltageIn_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_voltageIn_result.setObjectName(_fromUtf8("label_voltageIn_result"))
        self.label_turnIn_result = QtGui.QLabel(self.groupBox_input_result)
        self.label_turnIn_result.setGeometry(QtCore.QRect(10, 140, 120, 20))
        self.label_turnIn_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_turnIn_result.setObjectName(_fromUtf8("label_turnIn_result"))
        self.lineEdit_densityIn_result = QtGui.QLineEdit(self.groupBox_input_result)
        self.lineEdit_densityIn_result.setGeometry(QtCore.QRect(135, 165, 80, 20))
        self.lineEdit_densityIn_result.setObjectName(_fromUtf8("lineEdit_densityIn_result"))
        self.tabWidget.addTab(self.result_1, _fromUtf8(""))
        self.result_2 = QtGui.QWidget()
        self.result_2.setObjectName(_fromUtf8("result_2"))
        self.label_frequency_result = QtGui.QLabel(self.result_2)
        self.label_frequency_result.setGeometry(QtCore.QRect(10, 15, 140, 16))
        self.label_frequency_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_frequency_result.setObjectName(_fromUtf8("label_frequency_result"))
        self.label_induction_result = QtGui.QLabel(self.result_2)
        self.label_induction_result.setGeometry(QtCore.QRect(10, 45, 140, 16))
        self.label_induction_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_induction_result.setObjectName(_fromUtf8("label_induction_result"))
        self.label_density_result = QtGui.QLabel(self.result_2)
        self.label_density_result.setGeometry(QtCore.QRect(10, 75, 140, 16))
        self.label_density_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_density_result.setObjectName(_fromUtf8("label_density_result"))
        self.label_weightIron_result = QtGui.QLabel(self.result_2)
        self.label_weightIron_result.setGeometry(QtCore.QRect(10, 105, 140, 16))
        self.label_weightIron_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_weightIron_result.setObjectName(_fromUtf8("label_weightIron_result"))
        self.label_weightCopper_result = QtGui.QLabel(self.result_2)
        self.label_weightCopper_result.setGeometry(QtCore.QRect(10, 135, 140, 16))
        self.label_weightCopper_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_weightCopper_result.setObjectName(_fromUtf8("label_weightCopper_result"))
        self.label_turnAverageLength_result = QtGui.QLabel(self.result_2)
        self.label_turnAverageLength_result.setGeometry(QtCore.QRect(10, 165, 140, 16))
        self.label_turnAverageLength_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_turnAverageLength_result.setObjectName(_fromUtf8("label_turnAverageLength_result"))
        self.label_coilArea_result = QtGui.QLabel(self.result_2)
        self.label_coilArea_result.setGeometry(QtCore.QRect(10, 195, 140, 16))
        self.label_coilArea_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_coilArea_result.setObjectName(_fromUtf8("label_coilArea_result"))
        self.label_lossIron_result = QtGui.QLabel(self.result_2)
        self.label_lossIron_result.setGeometry(QtCore.QRect(240, 15, 100, 16))
        self.label_lossIron_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_lossIron_result.setObjectName(_fromUtf8("label_lossIron_result"))
        self.label_lossCopper_result = QtGui.QLabel(self.result_2)
        self.label_lossCopper_result.setGeometry(QtCore.QRect(240, 45, 100, 13))
        self.label_lossCopper_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_lossCopper_result.setObjectName(_fromUtf8("label_lossCopper_result"))
        self.label_totalLoss_result = QtGui.QLabel(self.result_2)
        self.label_totalLoss_result.setGeometry(QtCore.QRect(240, 75, 100, 13))
        self.label_totalLoss_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_totalLoss_result.setObjectName(_fromUtf8("label_totalLoss_result"))
        self.label_efficiency_result = QtGui.QLabel(self.result_2)
        self.label_efficiency_result.setGeometry(QtCore.QRect(240, 105, 100, 13))
        self.label_efficiency_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_efficiency_result.setObjectName(_fromUtf8("label_efficiency_result"))
        self.lineEdit_frequency_result = QtGui.QLineEdit(self.result_2)
        self.lineEdit_frequency_result.setGeometry(QtCore.QRect(155, 10, 80, 20))
        self.lineEdit_frequency_result.setObjectName(_fromUtf8("lineEdit_frequency_result"))
        self.lineEdit_induction_result = QtGui.QLineEdit(self.result_2)
        self.lineEdit_induction_result.setGeometry(QtCore.QRect(155, 40, 80, 20))
        self.lineEdit_induction_result.setObjectName(_fromUtf8("lineEdit_induction_result"))
        self.lineEdit_density_result = QtGui.QLineEdit(self.result_2)
        self.lineEdit_density_result.setGeometry(QtCore.QRect(155, 70, 80, 20))
        self.lineEdit_density_result.setObjectName(_fromUtf8("lineEdit_density_result"))
        self.lineEdit_weightIron_result = QtGui.QLineEdit(self.result_2)
        self.lineEdit_weightIron_result.setGeometry(QtCore.QRect(155, 100, 80, 20))
        self.lineEdit_weightIron_result.setObjectName(_fromUtf8("lineEdit_weightIron_result"))
        self.lineEdit_weightCopper_result = QtGui.QLineEdit(self.result_2)
        self.lineEdit_weightCopper_result.setGeometry(QtCore.QRect(155, 130, 80, 20))
        self.lineEdit_weightCopper_result.setObjectName(_fromUtf8("lineEdit_weightCopper_result"))
        self.lineEdit_turnAverageLength_result = QtGui.QLineEdit(self.result_2)
        self.lineEdit_turnAverageLength_result.setGeometry(QtCore.QRect(155, 160, 80, 20))
        self.lineEdit_turnAverageLength_result.setObjectName(_fromUtf8("lineEdit_turnAverageLength_result"))
        self.lineEdit_coilArea_result = QtGui.QLineEdit(self.result_2)
        self.lineEdit_coilArea_result.setGeometry(QtCore.QRect(155, 190, 80, 20))
        self.lineEdit_coilArea_result.setObjectName(_fromUtf8("lineEdit_coilArea_result"))
        self.lineEdit_lossIron_result = QtGui.QLineEdit(self.result_2)
        self.lineEdit_lossIron_result.setGeometry(QtCore.QRect(345, 10, 80, 20))
        self.lineEdit_lossIron_result.setObjectName(_fromUtf8("lineEdit_lossIron_result"))
        self.lineEdit_lossCopper_result = QtGui.QLineEdit(self.result_2)
        self.lineEdit_lossCopper_result.setGeometry(QtCore.QRect(345, 40, 80, 20))
        self.lineEdit_lossCopper_result.setObjectName(_fromUtf8("lineEdit_lossCopper_result"))
        self.lineEdit_totalLoss_result = QtGui.QLineEdit(self.result_2)
        self.lineEdit_totalLoss_result.setGeometry(QtCore.QRect(345, 70, 80, 20))
        self.lineEdit_totalLoss_result.setObjectName(_fromUtf8("lineEdit_totalLoss_result"))
        self.lineEdit_efficiency_result = QtGui.QLineEdit(self.result_2)
        self.lineEdit_efficiency_result.setGeometry(QtCore.QRect(345, 100, 80, 20))
        self.lineEdit_efficiency_result.setObjectName(_fromUtf8("lineEdit_efficiency_result"))
        self.tabWidget.addTab(self.result_2, _fromUtf8(""))
        self.groupBox_Input = QtGui.QGroupBox(DialogNew)
        self.groupBox_Input.setGeometry(QtCore.QRect(180, 10, 151, 111))
        self.groupBox_Input.setObjectName(_fromUtf8("groupBox_Input"))
        self.label_voltageIn = QtGui.QLabel(self.groupBox_Input)
        self.label_voltageIn.setGeometry(QtCore.QRect(10, 55, 50, 14))
        self.label_voltageIn.setObjectName(_fromUtf8("label_voltageIn"))
        self.label_powerIn = QtGui.QLabel(self.groupBox_Input)
        self.label_powerIn.setGeometry(QtCore.QRect(10, 25, 50, 14))
        self.label_powerIn.setObjectName(_fromUtf8("label_powerIn"))
        self.label_currentIn = QtGui.QLabel(self.groupBox_Input)
        self.label_currentIn.setGeometry(QtCore.QRect(10, 85, 50, 14))
        self.label_currentIn.setObjectName(_fromUtf8("label_currentIn"))
        self.lineEdit_powerIn = QtGui.QLineEdit(self.groupBox_Input)
        self.lineEdit_powerIn.setGeometry(QtCore.QRect(60, 20, 80, 20))
        self.lineEdit_powerIn.setObjectName(_fromUtf8("lineEdit_powerIn"))
        self.lineEdit_voltageIn = QtGui.QLineEdit(self.groupBox_Input)
        self.lineEdit_voltageIn.setGeometry(QtCore.QRect(60, 50, 80, 20))
        self.lineEdit_voltageIn.setObjectName(_fromUtf8("lineEdit_voltageIn"))
        self.lineEdit_currentIn = QtGui.QLineEdit(self.groupBox_Input)
        self.lineEdit_currentIn.setGeometry(QtCore.QRect(60, 80, 80, 20))
        self.lineEdit_currentIn.setObjectName(_fromUtf8("lineEdit_currentIn"))
        self.pushButton_saveProject = QtGui.QPushButton(DialogNew)
        self.pushButton_saveProject.setGeometry(QtCore.QRect(400, 538, 100, 35))
        self.pushButton_saveProject.setObjectName(_fromUtf8("pushButton_saveProject"))
        self.pushButton_closeProject = QtGui.QPushButton(DialogNew)
        self.pushButton_closeProject.setGeometry(QtCore.QRect(510, 538, 100, 35))
        self.pushButton_closeProject.setObjectName(_fromUtf8("pushButton_closeProject"))

        self.retranslateUi(DialogNew)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogNew)

    def retranslateUi(self, DialogNew):
        DialogNew.setWindowTitle(_translate("DialogNew", "Helena", None))
        self.groupBox_general.setTitle(_translate("DialogNew", "Informacoes Gerais", None))
        self.label_frequency.setText(_translate("DialogNew", "Frequencia:", None))
        self.lineEdit_frequency.setText(_translate("DialogNew", "60.0", None))
        self.label_tempReference.setText(_translate("DialogNew", "Temp. referencia:", None))
        self.lineEdit_tempReference.setText(_translate("DialogNew", "115.0", None))
        self.label_flux.setText(_translate("DialogNew", "Fluxo:", None))
        self.lineEdit_flux.setText(_translate("DialogNew", "11300.0", None))
        self.label_currentDensity.setText(_translate("DialogNew", "Densidade de Corrente:", None))
        self.lineEdit_currentDensity.setText(_translate("DialogNew", "3.0", None))
        self.label_style.setText(_translate("DialogNew", "Padrao Enrolamentos:", None))
        self.comboBox_style.setItemText(0, _translate("DialogNew", "1 primario / 1 secundario", None))
        self.comboBox_style.setItemText(1, _translate("DialogNew", "1 primario / 2 secundario", None))
        self.comboBox_style.setItemText(2, _translate("DialogNew", "2 primario / 1 secundario", None))
        self.comboBox_style.setItemText(3, _translate("DialogNew", "2 primario / 2 secundario", None))
        self.label_lamina.setText(_translate("DialogNew", "Tipo de Lamina:", None))
        self.comboBox_lamina.setItemText(0, _translate("DialogNew", "Padrao", None))
        self.comboBox_lamina.setItemText(1, _translate("DialogNew", "Comprida", None))
        self.comboBox_lamina.setItemText(2, _translate("DialogNew", "Com GAP", None))
        self.groupBox.setTitle(_translate("DialogNew", "Outras Informacoes", None))
        self.checkBox_compensation.setText(_translate("DialogNew", "Compensacao:", None))
        self.lineEdit_compensation.setText(_translate("DialogNew", "10.0", None))
        self.pushButton_calculate.setText(_translate("DialogNew", "Calcular Transformador", None))
        self.groupBox_Output.setTitle(_translate("DialogNew", "Informacoes de Saida", None))
        self.label_voltageOut.setText(_translate("DialogNew", "Tensao:", None))
        self.label_powerOut.setText(_translate("DialogNew", "Potencia:", None))
        self.label_currentOut.setText(_translate("DialogNew", "Corrente:", None))
        self.groupBox_output_result.setTitle(_translate("DialogNew", "Saida", None))
        self.label_powerOut_result.setText(_translate("DialogNew", "Potencia de Saida:", None))
        self.label_awgWireOut_result.setText(_translate("DialogNew", "Fio AWG de Saida:", None))
        self.label_densityOut_result.setText(_translate("DialogNew", "Densidade de Saida:", None))
        self.label_currentOut_result.setText(_translate("DialogNew", "Corrente de Saida:", None))
        self.label_voltageOut_result.setText(_translate("DialogNew", "Tensao de Saida:", None))
        self.label_turnOut_result.setText(_translate("DialogNew", "Nº de voltas na Saida:", None))
        self.groupBox_input_result.setTitle(_translate("DialogNew", "Entrada", None))
        self.label_powerIn_result.setText(_translate("DialogNew", "Potencia de Entrada:", None))
        self.label_awgWireIn_result.setText(_translate("DialogNew", "Fio AWG de Entrada:", None))
        self.label_densityIn_result.setText(_translate("DialogNew", "Densidade de Entrada:", None))
        self.label_currentIn_result.setText(_translate("DialogNew", "Corrente de Entrada:", None))
        self.label_voltageIn_result.setText(_translate("DialogNew", "Tensao de Entrada:", None))
        self.label_turnIn_result.setText(_translate("DialogNew", "Nº de voltas na Entrada:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.result_1), _translate("DialogNew", "Resultados 1/2", None))
        self.label_frequency_result.setText(_translate("DialogNew", "Frequencia:", None))
        self.label_induction_result.setText(_translate("DialogNew", "Inducao Magnetica:", None))
        self.label_density_result.setText(_translate("DialogNew", "Densidade Media:", None))
        self.label_weightIron_result.setText(_translate("DialogNew", "Peso do Ferro:", None))
        self.label_weightCopper_result.setText(_translate("DialogNew", "Peso do Cobre:", None))
        self.label_turnAverageLength_result.setText(_translate("DialogNew", "Comprimento Medio de Volta:", None))
        self.label_coilArea_result.setText(_translate("DialogNew", "Area dos enrolamentos:", None))
        self.label_lossIron_result.setText(_translate("DialogNew", "Perda no Ferro:", None))
        self.label_lossCopper_result.setText(_translate("DialogNew", "Perda no Cobre:", None))
        self.label_totalLoss_result.setText(_translate("DialogNew", "Perda Total:", None))
        self.label_efficiency_result.setText(_translate("DialogNew", "Eficiencia:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.result_2), _translate("DialogNew", "Resultados 2/2", None))
        self.groupBox_Input.setTitle(_translate("DialogNew", "Informacoes de Entrada", None))
        self.label_voltageIn.setText(_translate("DialogNew", "Tensao:", None))
        self.label_powerIn.setText(_translate("DialogNew", "Potencia:", None))
        self.label_currentIn.setText(_translate("DialogNew", "Corrente:", None))
        self.pushButton_saveProject.setText(_translate("DialogNew", "Salvar Projeto", None))
        self.pushButton_closeProject.setText(_translate("DialogNew", "Fechar Projeto", None))
        
        self.pushButton_calculate.clicked.connect(self.calculate)
        self.pushButton_saveProject.clicked.connect(self.saveDialog)
        self.pushButton_closeProject.clicked.connect(lambda: self.closeDialog(DialogNew))
    
    def saveDialog(self):
        fileName = QtGui.QFileDialog.getSaveFileName(None,"Salvar Projeto Helena", '', "Helena Projeto (*.hp);;XML files (*.xml);;All Files (*)")
        
        if not fileName:
            return
        
        try:
            #out_file = open(str(fileName), 'wb')
            print fileName
            print self.lineEdit_powerOut.text()
        except IOError:
            QtGui.QMessageBox.information(self, "Unable to open file", "There was an error opening \"%s\"" % fileName)
            return
        
    def closeDialog(self, DialogNew):
        DialogNew.close()
        
        
    def calculate(self):
        data_lamina = Laminas('laminas.xml')
        data_bobbin = Bobbins('bobbins.xml')
        data_wire = Wires('wires.xml')
        
        lamina = Lamina()
        bobbin = Bobbin()
        wireIN = Wire()
        wireOUT = Wire()
        
        tempReference = self.lineEdit_tempReference.text().toFloat()[0]
        #print tempReference
        typeLamina = self.comboBox_lamina.currentText() #self.comboBox_lamina.currentIndex()
        #print typeLamina
        state_compensation = self.checkBox_compensation.isChecked()
        #print state_compensation
        value_compensation = self.lineEdit_compensation.text().toFloat()[0]
        #print value_compensation
        
        lamina.setType( 'padrao' )
        bobbin.setType( 'padrao' )
        wireIN.setType( 'redondo' )
        wireOUT.setType( 'redondo' )
        
        transformer = Transformer()
        transformer.setPowerOUT( self.lineEdit_powerOut.text().toFloat()[0] )
        transformer.setVoltageOUT( self.lineEdit_voltageOut.text().toFloat()[0] )
        transformer.setCurrentOUT( self.lineEdit_currentOut.text().toFloat()[0] )
        
        transformer.setPowerIN( self.lineEdit_voltageIn.text().toFloat()[0] )
        transformer.setVoltageIN( self.lineEdit_voltageIn.text().toFloat()[0] )
        transformer.setCurrentIN( self.lineEdit_currentIn.text().toFloat()[0] )
        
        transformer.setFrequency( self.lineEdit_frequency.text().toFloat()[0] )
        transformer.setFlux( self.lineEdit_flux.text().toFloat()[0] )
        transformer.setCurrentDensity( self.lineEdit_currentDensity.text().toFloat()[0] )
        transformer.setStyle( self.comboBox_style.currentIndex() )
        transformer.setLamina( lamina )
        transformer.setBobbin( bobbin )
        transformer.setWireIN( wireIN )
        transformer.setWireOUT( wireOUT )
        
        if transformer.calculate() == False:
            self.lineEdit_powerOut_result.setText( str( round(transformer.getPowerOUT(),2) ) )
            self.lineEdit_voltageOut_result.setText( str( round(transformer.getVoltageOUT(),2) ) )
            self.lineEdit_currentOut_output.setText( str( round(transformer.getCurrentOUT(),2) ) )
            self.lineEdit_awgWireOut_result.setText( str( transformer.getWireOUT().getAWG() ) )
            self.lineEdit_turnOut_result.setText( str( round(transformer.getTurnsOUT(),2) ) )
            self.lineEdit_densityOut_result.setText( str( round(transformer.getCurrentDensityOUT(),2) ) )
            
            self.lineEdit_powerIn_result.setText( str( round(transformer.getPowerIN(),2) ) )
            self.lineEdit_voltageIn_result.setText( str( round(transformer.getVoltageIN(),2) ) )
            self.lineEdit_currentIn_result.setText( str( round(transformer.getCurrentIN(),2) ) )
            self.lineEdit_awgWireIn_result.setText( str( transformer.getWireIN().getAWG() ) )
            self.lineEdit_turnIn_result.setText( str( round(transformer.getTurnsIN(),2) ) )
            self.lineEdit_densityIn_result.setText( str( round(transformer.getCurrentDensityIN(),2) ) )
            
            self.lineEdit_frequency_result.setText( str( round(transformer.getFrequency(),2) ) )
            self.lineEdit_induction_result.setText( str( round(transformer.getFlux(),2) ) )
            self.lineEdit_density_result.setText( str( round(transformer.getCurrentDensity(),2) ) )
            self.lineEdit_weightIron_result.setText( str( round(transformer.getWeigthIron()*1000.0,2) ) )
            self.lineEdit_weightCopper_result.setText( str( round(transformer.getWeightCopper()*1000.0,2) ) )
            self.lineEdit_turnAverageLength_result.setText( str( round(transformer.getAverageLengthTurn()/10,2) ) )
            self.lineEdit_coilArea_result.setText( str( round(transformer.getCoilArea(),2) ) )
            self.lineEdit_lossIron_result.setText( str( round(transformer.getLossIron(),2) ) )
            self.lineEdit_lossCopper_result.setText( str( round(transformer.getLossCopper(),2) ) )
            self.lineEdit_totalLoss_result.setText( str( round(transformer.getLossIron()+transformer.getLossCopper(),2) ) )
            self.lineEdit_efficiency_result.setText( str( round(transformer.getEfficiency()*100,2) ) )
        else:
            iconW = QtGui.QIcon()
            iconW.addPixmap(QtGui.QPixmap(_fromUtf8("iconPower.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            iconN = QtGui.QPixmap(_fromUtf8("iconNotification.ico"))
            msgBox = QtGui.QMessageBox()
            msgBox.setWindowTitle(_translate(None, "Helena", None))
            msgBox.setText("Erro nas informacoes.")
            msgBox.setInformativeText("Por favor, reveja as informacoes contidas nos campos de entrada.")
            msgBox.setWindowIcon(iconW)
            msgBox.setIconPixmap(iconN)
            msgBox.exec_()
