# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowWire.ui'
#
# Created: Sun Sep 30 03:23:03 2018
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogWire(object):
    def setupUi(self, DialogWire):
        DialogWire.setObjectName(_fromUtf8("DialogWire"))
        DialogWire.resize(400, 299)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("iconWire.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogWire.setWindowIcon(icon)
        self.lineEdit_id = QtGui.QLineEdit(DialogWire)
        self.lineEdit_id.setGeometry(QtCore.QRect(80, 10, 113, 20))
        self.lineEdit_id.setReadOnly(True)
        self.lineEdit_id.setObjectName(_fromUtf8("lineEdit_id"))
        self.label_id = QtGui.QLabel(DialogWire)
        self.label_id.setGeometry(QtCore.QRect(10, 15, 70, 16))
        self.label_id.setObjectName(_fromUtf8("label_id"))
        self.label_awg = QtGui.QLabel(DialogWire)
        self.label_awg.setGeometry(QtCore.QRect(10, 45, 70, 16))
        self.label_awg.setObjectName(_fromUtf8("label_awg"))
        self.label_Area = QtGui.QLabel(DialogWire)
        self.label_Area.setGeometry(QtCore.QRect(210, 70, 31, 16))
        self.label_Area.setObjectName(_fromUtf8("label_Area"))
        self.lineEdit_diameter = QtGui.QLineEdit(DialogWire)
        self.lineEdit_diameter.setGeometry(QtCore.QRect(230, 35, 113, 20))
        self.lineEdit_diameter.setObjectName(_fromUtf8("lineEdit_diameter"))
        self.lineEdit_turnPerCm = QtGui.QLineEdit(DialogWire)
        self.lineEdit_turnPerCm.setGeometry(QtCore.QRect(80, 65, 71, 20))
        self.lineEdit_turnPerCm.setObjectName(_fromUtf8("lineEdit_turnPerCm"))
        self.lineEdit_area = QtGui.QLineEdit(DialogWire)
        self.lineEdit_area.setGeometry(QtCore.QRect(240, 60, 113, 20))
        self.lineEdit_area.setObjectName(_fromUtf8("lineEdit_area"))
        self.lineEdit_resistance = QtGui.QLineEdit(DialogWire)
        self.lineEdit_resistance.setGeometry(QtCore.QRect(80, 95, 61, 20))
        self.lineEdit_resistance.setObjectName(_fromUtf8("lineEdit_resistance"))
        self.label_resistance = QtGui.QLabel(DialogWire)
        self.label_resistance.setGeometry(QtCore.QRect(10, 100, 80, 16))
        self.label_resistance.setObjectName(_fromUtf8("label_resistance"))
        self.lineEdit_awg = QtGui.QLineEdit(DialogWire)
        self.lineEdit_awg.setGeometry(QtCore.QRect(80, 40, 71, 20))
        self.lineEdit_awg.setObjectName(_fromUtf8("lineEdit_awg"))
        self.label_diameter = QtGui.QLabel(DialogWire)
        self.label_diameter.setGeometry(QtCore.QRect(160, 40, 70, 16))
        self.label_diameter.setObjectName(_fromUtf8("label_diameter"))
        self.label_turnPerCm = QtGui.QLabel(DialogWire)
        self.label_turnPerCm.setGeometry(QtCore.QRect(10, 70, 70, 16))
        self.label_turnPerCm.setObjectName(_fromUtf8("label_turnPerCm"))
        self.lineEdit_weight = QtGui.QLineEdit(DialogWire)
        self.lineEdit_weight.setGeometry(QtCore.QRect(260, 95, 71, 20))
        self.lineEdit_weight.setObjectName(_fromUtf8("lineEdit_weight"))
        self.label_weight = QtGui.QLabel(DialogWire)
        self.label_weight.setGeometry(QtCore.QRect(210, 100, 80, 16))
        self.label_weight.setObjectName(_fromUtf8("label_weight"))
        self.label_length = QtGui.QLabel(DialogWire)
        self.label_length.setGeometry(QtCore.QRect(10, 135, 80, 16))
        self.label_length.setObjectName(_fromUtf8("label_length"))
        self.lineEdit_weight_2 = QtGui.QLineEdit(DialogWire)
        self.lineEdit_weight_2.setGeometry(QtCore.QRect(80, 130, 61, 20))
        self.lineEdit_weight_2.setObjectName(_fromUtf8("lineEdit_weight_2"))
        self.lineEdit_frequency = QtGui.QLineEdit(DialogWire)
        self.lineEdit_frequency.setGeometry(QtCore.QRect(260, 125, 71, 20))
        self.lineEdit_frequency.setObjectName(_fromUtf8("lineEdit_frequency"))
        self.label_frequency = QtGui.QLabel(DialogWire)
        self.label_frequency.setGeometry(QtCore.QRect(190, 130, 80, 16))
        self.label_frequency.setObjectName(_fromUtf8("label_frequency"))
        self.label_type = QtGui.QLabel(DialogWire)
        self.label_type.setGeometry(QtCore.QRect(210, 15, 70, 16))
        self.label_type.setObjectName(_fromUtf8("label_type"))
        self.lineEdit_awg_2 = QtGui.QLineEdit(DialogWire)
        self.lineEdit_awg_2.setGeometry(QtCore.QRect(280, 10, 113, 20))
        self.lineEdit_awg_2.setObjectName(_fromUtf8("lineEdit_awg_2"))
        self.label_unit_diameter = QtGui.QLabel(DialogWire)
        self.label_unit_diameter.setGeometry(QtCore.QRect(350, 40, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_unit_diameter.setFont(font)
        self.label_unit_diameter.setObjectName(_fromUtf8("label_unit_diameter"))
        self.label_unit_turnPerCm = QtGui.QLabel(DialogWire)
        self.label_unit_turnPerCm.setGeometry(QtCore.QRect(160, 70, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_unit_turnPerCm.setFont(font)
        self.label_unit_turnPerCm.setObjectName(_fromUtf8("label_unit_turnPerCm"))
        self.label_unit_area = QtGui.QLabel(DialogWire)
        self.label_unit_area.setGeometry(QtCore.QRect(360, 60, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_unit_area.setFont(font)
        self.label_unit_area.setObjectName(_fromUtf8("label_unit_area"))
        self.label_unit_resistance = QtGui.QLabel(DialogWire)
        self.label_unit_resistance.setGeometry(QtCore.QRect(150, 100, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_unit_resistance.setFont(font)
        self.label_unit_resistance.setObjectName(_fromUtf8("label_unit_resistance"))
        self.label_unit_weight = QtGui.QLabel(DialogWire)
        self.label_unit_weight.setGeometry(QtCore.QRect(340, 100, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_unit_weight.setFont(font)
        self.label_unit_weight.setObjectName(_fromUtf8("label_unit_weight"))
        self.label_unit_length = QtGui.QLabel(DialogWire)
        self.label_unit_length.setGeometry(QtCore.QRect(150, 130, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_unit_length.setFont(font)
        self.label_unit_length.setObjectName(_fromUtf8("label_unit_length"))
        self.label_unit_frequency = QtGui.QLabel(DialogWire)
        self.label_unit_frequency.setGeometry(QtCore.QRect(340, 130, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_unit_frequency.setFont(font)
        self.label_unit_frequency.setObjectName(_fromUtf8("label_unit_frequency"))
        self.groupBox = QtGui.QGroupBox(DialogWire)
        self.groupBox.setGeometry(QtCore.QRect(20, 160, 351, 101))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.listView_currentMax = QtGui.QListView(self.groupBox)
        self.listView_currentMax.setGeometry(QtCore.QRect(10, 20, 331, 71))
        self.listView_currentMax.setObjectName(_fromUtf8("listView_currentMax"))
        self.pushButton_exit = QtGui.QPushButton(DialogWire)
        self.pushButton_exit.setGeometry(QtCore.QRect(310, 270, 82, 23))
        self.pushButton_exit.setObjectName(_fromUtf8("pushButton_exit"))
        self.pushButton_insert = QtGui.QPushButton(DialogWire)
        self.pushButton_insert.setGeometry(QtCore.QRect(225, 270, 80, 23))
        self.pushButton_insert.setObjectName(_fromUtf8("pushButton_insert"))
        self.pushButton_after = QtGui.QPushButton(DialogWire)
        self.pushButton_after.setGeometry(QtCore.QRect(75, 270, 60, 23))
        self.pushButton_after.setObjectName(_fromUtf8("pushButton_after"))
        self.pushButton_edit = QtGui.QPushButton(DialogWire)
        self.pushButton_edit.setGeometry(QtCore.QRect(140, 270, 80, 23))
        self.pushButton_edit.setObjectName(_fromUtf8("pushButton_edit"))
        self.pushButton_before = QtGui.QPushButton(DialogWire)
        self.pushButton_before.setGeometry(QtCore.QRect(10, 270, 60, 23))
        self.pushButton_before.setObjectName(_fromUtf8("pushButton_before"))

        self.retranslateUi(DialogWire)
        QtCore.QMetaObject.connectSlotsByName(DialogWire)

    def retranslateUi(self, DialogWire):
        DialogWire.setWindowTitle(_translate("DialogWire", "Helena Power - Fios", None))
        self.label_id.setText(_translate("DialogWire", "ID:", None))
        self.label_awg.setText(_translate("DialogWire", "AWG:", None))
        self.label_Area.setText(_translate("DialogWire", "Area:", None))
        self.label_resistance.setText(_translate("DialogWire", "Resistencia:", None))
        self.label_diameter.setText(_translate("DialogWire", "Diametro:", None))
        self.label_turnPerCm.setText(_translate("DialogWire", "Espiras/cm:", None))
        self.label_weight.setText(_translate("DialogWire", "Peso:", None))
        self.label_length.setText(_translate("DialogWire", "Comprimento:", None))
        self.label_frequency.setText(_translate("DialogWire", "Frequencia:", None))
        self.label_type.setText(_translate("DialogWire", "Tipo:", None))
        self.label_unit_diameter.setText(_translate("DialogWire", "mm", None))
        self.label_unit_turnPerCm.setText(_translate("DialogWire", "esp/cm", None))
        self.label_unit_area.setText(_translate("DialogWire", "mm^2", None))
        self.label_unit_resistance.setText(_translate("DialogWire", "Ohm/km", None))
        self.label_unit_weight.setText(_translate("DialogWire", "kg/km", None))
        self.label_unit_length.setText(_translate("DialogWire", "m/kg", None))
        self.label_unit_frequency.setText(_translate("DialogWire", "kHz", None))
        self.groupBox.setTitle(_translate("DialogWire", "Corrente Maxima", None))
        self.pushButton_exit.setText(_translate("DialogWire", "Sair", None))
        self.pushButton_insert.setText(_translate("DialogWire", "Inserir", None))
        self.pushButton_after.setText(_translate("DialogWire", ">>", None))
        self.pushButton_edit.setText(_translate("DialogWire", "Editar", None))
        self.pushButton_before.setText(_translate("DialogWire", "<<", None))

